### ISSUE TITLE
customization of 'migration' subdirectory, relaying on frameworks module aliases

### ISSUE THREAD

**Issue by redguy666** [yiiext/migrate-command#12]
This is my simple improvement to your extension. Basically there are two changes:
I need to configure where relation files are on disk (relative to core/module path) so I added 'moduleMigrationsDirectory' public attribute which points to 'migrations' by default.
Other change apply to getModulePaths function: instead of pointing

``` php
$alias =  'application.modules.' . $module . '.migrations';
```

I would rather do:

``` php
$alias = $module . '.' . $this->moduleMigrationsDirectory;
```

This work as Yii by default creates alias for every module defined. alias is same as module id and points to root directory of that module.

whole function looks like this:

``` php
<?php
    public function getModulePaths() {
        if( $this->_modulePaths === null ) {
            $this->_modulePaths = array();
            foreach( Yii::app()->modules as $module => $config ) {
                if( is_array( $config ) ) {
                    $alias = $module . '.' . $this->moduleMigrationsDirectory;
                    $this->_modulePaths[ $module ] = $alias;
                    $path = Yii::getPathOfAlias( $alias );
                    if( $path === false || !is_dir( $path ) ) {
                        $this->_disabledModules[] = $module;
                    }
                } else {
                    $this->_modulePaths[ $config ] = $config . '.' . $this->moduleMigrationsDirectory;
                }
            }
        }
        // add a pseudo-module 'core'
        $this->_modulePaths[ $this->applicationModuleName ] = $this->migrationPath;
        $path = Yii::getPathOfAlias( $this->migrationPath );
        if( $path === false || !is_dir( $path ) ) {
            $this->_disabledModules[] = $this->applicationModuleName;
        }
        return $this->_modulePaths;
    }
```

I can provide patch/modified version od EMigrateCommand, but I can't do this here (or I am missing something...)

**Comment by redguy666** [comment]
damn... I am new to github. forgive my closing/opening tickets...

**Comment by cebe** [comment]
> I can provide patch/modified version od EMigrateCommand, but I can't do this here (or I am missing something...)

Thanks for sharing this, didn't check your changes in detail, but you could [fork](http://help.github.com/fork-a-repo/) my repo, create a branch, commit your changes there and start a [pull request](http://help.github.com/send-pull-requests/).

**Comment by cebe** [comment]
The change with the module alias would not work for modules that are defined with `'module'=>array('class'=>'...')` in the config since this alias is generated when the module is instantiated which we do not need for db migrations.
Is there anything that does not work with the current solution, or is your suggestion just cosmetic?

**Comment by cebe** [comment]
Okay, you wanted to have the modules from yii application but do not want the subdirectory be named `migrations` but somthing else?

**Comment by redguy666** [comment]
well.. for CWebApplication module aliases work always because YiiBase::getPathOfAlias has this code:

if(self::$_app instanceof CWebApplication) {
            if(self::$_app->findModule($rootAlias)!==null)
                return self::getPathOfAlias($alias);
        }

but it needs to load and initialize the module like you said. on the other hand this is not so big overhead (module initialization is mostly setting some import directories). Big advantage of such approach is that you do not clone code mapping module id to module path and use the default one provided by framework. Your code assumes that modules are in protected/modules directory ('application.modules.' . $module) which is not always true (I am working now on projects which involves 3 separate applications with common module directory which is not in 'protected' folder)...

it is just my opinion that relaying on frameworks path resolution would be better in most cases with just a little side effect of initializing all modules... :)

thanks for the migrations subdirectory customization! I am extensively using your extension (with just small changes which I described above). It is really nice work, because I can encapsulate module files in one directory (have similiar solutions for unit tests).

**Comment by cebe** [comment]
> but it needs to load and initialize the module like you said. on the other hand this is not so big overhead (module 
> initialization is mostly setting some import directories). 

thats the common case, but what if in Module::init() someone calls Yii::app()->... with something that is not available in console application?

> Your code assumes that modules are in protected/modules directory ('application.modules.' . $module) which is not 
> always true (I am working now on projects which involves 3 separate applications with common module directory which is 
> not in 'protected' folder)...

thats why I check the config for basePath and class alias. How are you adding your module when not with one of these ways?

> thanks for the migrations subdirectory customization! I am extensively using your extension (with just small changes which 
> I described above). It is really nice work, because I can encapsulate module files in one directory (have similiar solutions for unit tests).

Glad to hear it is usefull :-)

**Comment by cebe** [comment]
btw @redguy666 which dbms are you using?

**Comment by redguy666** [comment]
Mostly mysql and postgresql. we have some solutions which should work on
both of them. This is why I found this inconsistency in datetime metatype
:-) We also use oracle for few applicatons but we are using there legacy
DbMaintain versionning.
Why you asked?
17-02-2012 19:40 uytkownik "CeBe" <
reply@reply.github.com>
napisa:

**Comment by cebe** [comment]
just interested because with issue #3 I tried to support any dbms thats supported by PDO and I want to know if it works for all of them :-)

**Comment by cebe** [comment]
any further input here or is all fixed by 8bcb371 ?

**Comment by redguy666** [comment]
customization of migrations directory is fine for me :)

**Comment by cebe** [comment]
Great, thanks!
