### ISSUE TITLE
Attribute CDbMigration->interactive doesn't exists when migrating up

### ISSUE THREAD

**Issue by thiromi** [yiiext/migrate-command#2]
I don't think this is a bug, just missing documentation. I had to extend EDbMigration instead of default CDbMigration in order to get migration working on Yii 1.1.8 (not tried on other versions) and thought that this should be on documentation.

Anyway, excellent extension, dude!

**Comment by cebe** [comment]
Thank you for the feedback, this has been mentioned in a comment on the yii extension site and I fixed it in version [0.6.0](https://github.com/yiiext/migrate-command/tree/0.6.0) which was not released due to a problem with mysql.
Will fix this in a few days.

**Comment by thiromi** [comment]
Aw, snap! Didn't see it. But appreciated your response!

**Comment by dmtrs** [comment]
Is this --interactive=false respected with current version?

**Comment by dmtrs** [comment]
My bad it should be --interactive=0
